### ISSUE TITLE
Custom effect is not working

### ISSUE THREAD

**Issue by thierryskoda** [indrimuska/angular-counter#3]
I get the error : jQuery.easing[this.easing] is not a function

when trying to add a custom effect like : 'easeInOutElastic'

`<div counter to="1000" value="myValue" effect="easeInCubic"> {{myValue | number:0}} </div>`

I tried "easeInCubic" and "  'easeInCubic'  ".

Thank you, Thierry

**Comment by indrimuska** [comment]
Hi @thierryskoda,
If you add the quotes around your easing name `'easeInCubic'` it has to work.
Are you sure you have included the `jquery.easing` file in your app?

I created a set of examples that maybe can help to get Angular Counter more easy to use, I will put this Plunker in the readme file.
http://plnkr.co/edit/d1KPDa?p=preview

Let me know if one of these examples could help you.

**Comment by thierryskoda** [comment]
<img width="289" alt="screen shot 2015-11-30 at 3 13 37 pm" src="https://cloud.githubusercontent.com/assets/6875849/11483175/10c4e510-9775-11e5-947f-7f92239d4266.png">

This is what I have. And I still get this error even with `'easeInCubic'`

<img width="426" alt="screen shot 2015-11-30 at 3 15 39 pm" src="https://cloud.githubusercontent.com/assets/6875849/11483218/4b22c844-9775-11e5-9012-1803cef203c5.png">

**Comment by indrimuska** [comment]
Ok, looking at your error, I am almost sure you are using a configuration like this:

``` html
<script src="[..]/jquery.js"></script>
<script src="[..]/angular.js"></script>
<script src="[..]/angular-counter.js"></script>
```

As I say, you forgot to include `jquery.easing` file into your app, or at least you have to include the all-in-one file `angular-counter-with-easing`. So, you can use any of these configurations:

**jQuery + jQuery Easing + Angular + Angular Counter**

``` html
<script src="[..]/jquery.min.js"></script>
<script src="[..]/jquery.easing.min.js"></script>
<script src="[..]/angular.min.js"></script>
<script src="[..]/angular-counter.min.js"></script>
```

**jQuery + Angular + Angular Counter with jQuery Easing**

``` html
<script src="[..]/jquery.min.js"></script>
<script src="[..]/angular.min.js"></script>
<script src="[..]/angular-counter-with-easing.min.js"></script>
```

**Comment by indrimuska** [comment]
I'm going to close this issue because I assume the above comment should resolve your issue.
If not, please feel free to re-open it anytime! :)
