### ISSUE TITLE
Multiple Counters on Same Page

### ISSUE THREAD

**Issue by chipallen2** [indrimuska/angular-counter#7]
If I have multiple counters on one page - only the first one is getting the animation applied. Is that expected? Is there a workaround?

```
<td counter value="v" to="vNew" duration="400" effect="linear" finish="vFinished()">{{v}} </td>
<td counter value="v2" to="v2New" duration="400" effect="linear" finish="v2Finished()">{{v2}} </td>
```

Only the first one is getting the animation. The other one changes but just like normal.

**Comment by indrimuska** [comment]
Hi @chipallen2, could you please provide a full working sample with [plunker](https://plnkr.co/edit/?p=catalogue)/[fiddle](https://jsfiddle.net/)/[codepen](https://codepen.io/pen) to reproduce this issue? Many thanks :)

**Comment by chipallen2** [comment]
I tried recreating it in jsfiddle and couldn't. It works fine. The error must have been somewhere else in my code. Thanks for the great work on this plugin. It is very useful.

https://jsfiddle.net/chipallen2/vcf8rcas/

**Comment by indrimuska** [comment]
Ok, thanks for the kind words!
